[build]
builder = "nixpacks"
buildCommand = "cd backend && ./mvnw clean install -DskipTests"

[deploy]
startCommand = "java -jar backend/target/*.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
